import type { CareerTrack } from "@/lib/opportunities/types";

export const CAREER_TRACKS: CareerTrack[] = [
  {
    code: "enem-2026",
    title: "ENEM 2026",
    institution: "Inep",
    area: "educacional",
    scope: "Nacional",
    educationRequirement: "none",
    hasPhysicalTest: false,
    summary: "Aplicação regular em 8 e 15 de novembro de 2026, com quatro áreas do conhecimento, 180 questões objetivas e redação.",
    topicWeights: { "LING.INTERPRETACAO": 1, "RED.COMPETENCIAS": 1, "MAT.PROBLEMAS": 1, "HUM.HISTORIA": .86, "HUM.GEOGRAFIA": .86, "HUM.FILOSOFIA_SOCIOLOGIA": .72, "NAT.BIOLOGIA": .86, "NAT.FISICA": .86, "NAT.QUIMICA": .86 },
    examDates: ["2026-11-08", "2026-11-15"],
    officialSourceUrl: "https://www.gov.br/inep/pt-br/areas-de-atuacao/avaliacao-e-exames-educacionais/enem/orientacoes/cronograma",
  },
  {
    code: "pmmg-cfsd",
    title: "Polícia Militar — Soldado",
    institution: "Polícias Militares",
    area: "policial",
    scope: "Estadual",
    educationRequirement: "medio",
    hasPhysicalTest: true,
    summary: "Trilha-base para carreiras policiais militares, sujeita ao edital de cada estado.",
    topicWeights: { "LING.INTERPRETACAO": .75, "RLM.PROPOSICOES": .7, "CONST.DIREITOS_FUNDAMENTAIS": .9, "LEG.ETICA_DISCIPLINA": 1, "GERAL.CIDADANIA": .65 },
  },
  {
    code: "pmmg-cfo",
    title: "Polícia Militar — Oficial",
    institution: "Polícias Militares",
    area: "policial",
    scope: "Estadual",
    educationRequirement: "superior",
    hasPhysicalTest: true,
    summary: "Trilha de formação de oficiais com maior ênfase jurídica e requisitos definidos por edital.",
    topicWeights: { "LING.INTERPRETACAO": .8, "RLM.PROPOSICOES": .55, "CONST.DIREITOS_FUNDAMENTAIS": 1, "LEG.ETICA_DISCIPLINA": .9, "GERAL.CIDADANIA": .6 },
  },
  {
    code: "federal-police",
    title: "Carreiras policiais federais",
    institution: "Órgãos policiais federais",
    area: "policial",
    scope: "Federal",
    educationRequirement: "superior",
    hasPhysicalTest: true,
    summary: "Base de conhecimentos reaproveitável; cargos, etapas e requisitos variam por órgão e edital.",
    topicWeights: { "LING.INTERPRETACAO": .8, "RLM.PROPOSICOES": .85, "CONST.DIREITOS_FUNDAMENTAIS": 1, "LEG.ETICA_DISCIPLINA": .65, "GERAL.CIDADANIA": .45 },
  },
  {
    code: "courts",
    title: "Tribunais",
    institution: "Tribunais e órgãos jurídicos",
    area: "juridica",
    scope: "Nacional",
    educationRequirement: "medio",
    hasPhysicalTest: false,
    summary: "Trilha geral para áreas administrativa e judiciária, sem representar um edital específico.",
    topicWeights: { "LING.INTERPRETACAO": 1, "RLM.PROPOSICOES": .65, "CONST.DIREITOS_FUNDAMENTAIS": .9, "LEG.ETICA_DISCIPLINA": .25, "GERAL.CIDADANIA": .35 },
  },
  {
    code: "fiscal",
    title: "Carreira fiscal",
    institution: "Fiscos estaduais e municipais",
    area: "fiscal",
    scope: "Nacional",
    educationRequirement: "superior",
    hasPhysicalTest: false,
    summary: "Núcleo comum inicial para fiscos; disciplinas especializadas entram após a escolha do edital.",
    topicWeights: { "LING.INTERPRETACAO": .7, "RLM.PROPOSICOES": 1, "CONST.DIREITOS_FUNDAMENTAIS": .7, "LEG.ETICA_DISCIPLINA": .15, "GERAL.CIDADANIA": .35 },
  },
  {
    code: "administrative",
    title: "Área administrativa",
    institution: "Órgãos públicos diversos",
    area: "administrativa",
    scope: "Nacional",
    educationRequirement: "medio",
    hasPhysicalTest: false,
    summary: "Trilha exploratória de alta reutilização para quem ainda está escolhendo um órgão.",
    topicWeights: { "LING.INTERPRETACAO": 1, "RLM.PROPOSICOES": .8, "CONST.DIREITOS_FUNDAMENTAIS": .6, "LEG.ETICA_DISCIPLINA": .3, "GERAL.CIDADANIA": .55 },
  },
];
